spring:
  profiles.active: production
  application:
      name: dvla-search
  jackson:
      serialization:
          indent_output: true
dvla:
  search:
    endpoint: https://dvlasearch.appspot.com/DvlaSearch
    proxy:
      enabled: false
      host:
      port:
      user:
      pass:
    api:
      key: DvlaSearchDemoAccount
---
spring:
    profiles: production
server:
    port: 8080
---
spring:
    profiles: development
server:
    port: 8686
dvla:
  search:
    proxy:
      enabled: true
      host:
      port:
      user:
      pass:
